### ISSUE TITLE
Register is not exposed in django_register.__init__

### ISSUE THREAD

**Issue by Alexerson** [MaxDude132/django-register-field#2]
`from django_register import Register` is not possible. You need to do `from django_register.base import Register`.

The readme says otherwise.

**Comment by Alexerson** [comment]
:thinking: It actually looks good in the code. I think the pypi version is not up-to-date though.

**Comment by MaxDude132** [comment]
It's possible, it should be fixed automatically after version 1.0.1 to fix the other issues
