### ISSUE TITLE
Using the `Register` method doesn’t work properly

### ISSUE THREAD

**Issue by Alexerson** [MaxDude132/django-register-field#3]
The initialization fails with:
```
  File "/home/alex/Projects/django-register-field/tests/models.py", line 41, in <module>
    class City(models.Model):
  File "/home/alex/Projects/django-register-field/tests/models.py", line 45, in City
    planet = RegisterField(register=planets_register, default=Earth)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/Projects/django-register-field/django_register/base.py", line 144, in __init__
    kwargs["max_length"] = self.register.max_length
                           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/Projects/django-register-field/django_register/base.py", line 71, in max_length
    return max(len(key) for key in self._key_to_class)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: max() arg is an empty sequence
```

I’m assuming this is happening because `ready` is called after the model is initialized, and therefore the register doesn’t contain anything yet.

Do we really need to do that in the `ready` and not simply in `models.py` for instance?

**Comment by Alexerson** [comment]
And even if I manually set the `max_choices`, the generation of migrations still fails because the choices list is empty.

**Comment by MaxDude132** [comment]
You're right, it doesn't have to be in the the `ready` function, it can be directly in the `models.py`. I'll update the README. However, the issue for max_length is something that should not happen, so I'll have it be autogenerated only when there are values.
